# Generated by Django 3.2.5 on 2021-08-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=50)),
                ('gameID0', models.CharField(max_length=50)),
                ('gameID1', models.CharField(max_length=50)),
                ('gameID2', models.CharField(max_length=50)),
                ('gameID3', models.CharField(max_length=50)),
                ('amiiboUsage', models.CharField(max_length=256)),
                ('amiiboUsagewrite', models.BooleanField(default=False)),
            ],
        ),
    ]
